name: Sync S3 for Frontend

on: 
  workflow_dispatch:

permissions: 
  id-token: write
  contents: read

jobs:
  syncS3:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4
    
      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::779679300431:role/github-aws-oidc
          aws-region: ap-south-1

      - name: AWS S3 Sync
        run: aws s3 sync ./frontend s3://frontend-bucket-terraform-2026
