name: Testing the OICD connection

on:
  workflow_dispatch: 
permissions: 
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
        
      - name: AWS login OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::779679300431:role/github-to-aws-oicd
          aws-region: ap-south-1

      - name: Check a service
        run: aws s3api list-objects-v2 --bucket s3://amzn-s3-expense-tracker-application --query 'Contents[].Key' --output text   

